sudo: required
language: python
services:
   - docker
before_install:
   - docker build -t myatminsoe/webpage:v1 .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
   - docker push myatminsoe/webpage:v1
script:
   - docker run -p 8000 myatminsoe/webpage:v1
